### ISSUE TITLE
用的uniapp怎么导入这个库呢，正式版小程序朋友圈分享也是报的APP-SERVICE-SDK:lanDebug:fail rejected due错

### ISSUE THREAD

**Issue by clearht123** [youngjunning/wx-promise-pro#46]

**Comment by youngjuning** [comment]
看起来是官方的问题，https://developers.weixin.qq.com/community/develop/doc/00020636798248eaeb9aa476051400

**Comment by clearht123** [comment]
有什么办法嘛，微信的坑啊

**Comment by youngjuning** [comment]
你应该是自己有用到分享到朋友圈吧，看看社区怎么解决的可以，这种 API 限制比较多

**Comment by clearht123** [comment]
嗯谢谢，社区也没看到什么好的方法。

**Comment by youngjuning** [comment]
> 嗯谢谢，社区也没看到什么好的方法。

看起来是某个版本 SDK 的问题，可以试试换版本
